- name: Create AMI for EC2 instance Root Volume
  hosts: localhost

  tasks:
  
    - name: create ami for ec2 instance root volume 
      ec2_ami:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
        instance_id: "{{ instance_id }}"
        name: "{{ ami_name }}" 
        no_reboot: yes
        delete_snapshot: yes
        wait: yes
        tags:
          Name: "{{ ami_name }}" 
        device_mapping:
          - device_name: '/dev/xvda'
            volume_type: 'gp2'
            delete_on_termination: true
      register: ami_result
      
    - name: degug
      debug:
        msg: "{{ ami_result }}"