- name: VPC Deletions for All deps
  hosts: localhost

  tasks:
  
  - name: Setup AWS CLI aws_access_key
    shell: >
      aws configure set aws_access_key_id "{{ aws_access_key }}"

  - name: Setup AWS CLI aws_secret_key
    shell: >
      aws configure set aws_secret_access_key "{{ aws_secret_key }}"
      
  - name: Setup AWS CLI aws_region
    shell: >
      aws configure set region {{ aws_region }}  
  
  - name: Setup AWS CLI aws_region
    shell: >
      aws ec2 describe-internet-gateways --filters 'Name=attachment.vpc-id,Values='"{{ vpc_id }}" | grep InternetGatewayId
      aws ec2 describe-subnets --filters 'Name=vpc-id,Values='"{{ vpc_id }}" | grep SubnetId
      aws ec2 describe-route-tables --filters 'Name=vpc-id,Values='"{{ vpc_id }}" | grep RouteTableId
      aws ec2 describe-network-acls --filters 'Name=vpc-id,Values='"{{ vpc_id }}" | grep NetworkAclId
      aws ec2 describe-vpc-peering-connections --filters 'Name=requester-vpc-info.vpc-id,Values='"{{ vpc_id }}" | grep VpcPeeringConnectionId
      aws ec2 describe-vpc-endpoints --filters 'Name=vpc-id,Values='"{{ vpc_id }}" | grep VpcEndpointId
      aws ec2 describe-nat-gateways --filter 'Name=vpc-id,Values='"{{ vpc_id }}" | grep NatGatewayId
      aws ec2 describe-security-groups --filters 'Name=vpc-id,Values='"{{ vpc_id }}" | grep GroupId
      aws ec2 describe-instances --filters 'Name=vpc-id,Values='"{{ vpc_id }}" | grep InstanceId
      aws ec2 describe-vpn-connections --filters 'Name=vpc-id,Values='"{{ vpc_id }}" | grep VpnConnectionId
      aws ec2 describe-vpn-gateways --filters 'Name=attachment.vpc-id,Values='"{{ vpc_id }}" | grep VpnGatewayId
      aws ec2 describe-network-interfaces --filters 'Name=vpc-id,Values='"{{ vpc_id }}"| grep NetworkInterfaceId
      aws ec2 delete-vpc --vpc-id "{{ vpc_id }}"