- name: VPC Deletions
  hosts: localhost

  tasks:

    - name: DELETE THE VPC
      ec2_vpc_net:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"    
        name: "{{ vpc_name }}"  
        cidr_block: "{{ vpc_net_cidr }}".  
        region: "{{ aws_region }}"  
        state: absent  
        purge_cidrs: yes  
      register: my_vpc

    - name: degug vpc name
      debug:
        msg: "{{ my_vpc }}"

