- name: VPC Deletions for All deps
  hosts: localhost

  tasks:
  
  - name: Setup AWS CLI aws_access_key
    shell: >
      aws configure set aws_access_key_id "{{ aws_access_key }}"

  - name: Setup AWS CLI aws_secret_key
    shell: >
      aws configure set aws_secret_access_key "{{ aws_secret_key }}"
      
  - name: Setup AWS CLI aws_region
    shell: >
      aws configure set region {{ aws_region }}  
  
  - name: Setup AWS CLI InternetGatewayId
    shell: >
       aws ec2 describe-internet-gateways --filters 'Name=attachment.vpc-id,Values="{{ vpc_id }}"' | grep InternetGatewayId
    register: InternetGatewayId

  - name: Set InternetGatewayId in variable
    set_fact:
      my_InternetGatewayId: "{{ InternetGatewayId.gateway_id }}"

  - name: degug InternetGatewayId
    debug:
       msg: "{{ InternetGatewayId }}"

  - name: Setup AWS CLI InternetGatewayId
    shell: >
       aws ec2 delete-internet-gateway --internet-gateway-id "{{ my_InternetGatewayId }}"
    register: InternetGatewayIddelete

  - name: degug delete InternetGatewayId
    debug:
       msg: "{{ InternetGatewayIddelete }}"    