- name: VPC Deletions
  hosts: localhost

  tasks:

    - name: Delete VPC
      ec2_vpc_net:
        state: absent
        region: "{{ aws_region }}"
        cidr_block: "{{vpc_cidr_block}}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"      
      register: my_vpc

    - name: degug vpc name
      debug:
        msg: "{{ my_vpc }}"

