- name: S3 bucket create with static website Setup
  hosts: localhost

  tasks:

   - s3_bucket:
      name: "{{ bucket_name }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      state: present
      region: "{{ aws_region }}"
      versioning: "{{ bucket_version }}"
      tags:
         name: "{{ bucket_name }}"
         type: Development

   - s3_website:
      name: "{{ bucket_name }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      state: present
      region: "{{ aws_region }}"
      suffix: index.html
      error_key: errors/404.htm
     register: my_s3_website

   - name: degug s3 bucket deletion
     debug:
        msg: "{{ my_s3_website }}"