- name: VPC Create
  hosts: localhost

  tasks:

      - ec2_vpc_net:
          name: "{{ vpc_name }}"
          cidr_block: "{{ vpc_cidr_block }}"
          region: "{{ aws_region }}"
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          state: "present"
        register: my_vpc

      - name: degug vpc name
        debug:
          msg: "{{ my_vpc }}"